"use strict";

var inAppProducts = [];

inAppProducts["color_palette_background"] = { sku: "color_palette_background", title: "Palette of 127 background colors", description: '<img src="../img/colormap.png">' };

inAppProducts["color_box_background_purple_1"] = { sku: "color_box_background_purple_1", title: "Background box purple", description: '<div class="colorbox5" style="background: -webkit-linear-gradient(left, #9900cc 0%,#9900cc 20%, #cc00ff 20%, #cc00ff 40%, #cc33ff 40%,#cc33ff 60%, #cc66ff 60%,#cc66ff 80%, #cc99ff 80%, #cc99ff 100%);"></div>', colors: ['#9900cc', '#cc00ff', '#cc33ff', '#cc66ff', '#cc99ff'] };
inAppProducts["color_box_background_blue_1"] = { sku: "color_box_background_blue_1", title: "Background box blue", description: '<div class="colorbox5" style="background: -webkit-linear-gradient(left, #0000ff 0%, #0000ff 20%,#0066ff 20%,#0066ff 40%, #0099ff 40%,#0099ff 60%, #3399ff 60%,#3399ff 80%, #6699ff 80%, #6699ff 100%);"></div>', colors: ['#0000ff', '#0066ff', '#0099ff', '#3399ff', '#6699ff'] };
inAppProducts["color_box_background_green_1"] = { sku: "color_box_background_green_1", title: "Background box green", description: '<div class="colorbox5" style="background: -webkit-linear-gradient(left, #006600 0%,#006600 20%, #009933 20%, #009933 40%, #33cc33 40%,#33cc33 60%, #66ff66 60%,#66ff66 80%, #99ff99 80%, #99ff99 100%);"></div>', colors: ['#006600', '#009933', '#33cc33', '#66ff66', '#99ff99'] };
inAppProducts["color_box_background_pink_1"] = { sku: "color_box_background_pink_1", title: "Background box pink", description: '<div class="colorbox5" style="background: -webkit-linear-gradient(left, #cc0099 0%,#cc0099 20%, #ff33cc 20%, #ff33cc 40%, #ff66ff 40%,#ff66ff 60%, #ff99ff 60%,#ff99ff 80%, #ffccff 80%, #ffccff 100%);"></div>', colors: ['#cc0099', '#ff33cc', '#ff66ff', '#ff99ff', '#ffccff'] };
inAppProducts["color_box_background_red_1"] = { sku: "color_box_background_red_1", title: "Background box red", description: '<div class="colorbox5" style="background: -webkit-linear-gradient(left, #800000 0%,#800000 20%, #990000 20%, #990000 40%, #cc0000 40%,#cc0000 60%, #ff0000 60%,#ff0000 80%, #ff5050 80%, #ff5050 100%);"></div>', colors: ['#800000', '#990000', '#cc0000', '#ff0000', '#ff5050'] };

inAppProducts["speech_to_text"] = { sku: "speech_to_text", title: "Speech recognition.", description: '<img src="../img/microphone.jpg" style="float: left;margin-right: 15px;"><p style="font-size: 1.3em;">Create notes using your voice!<br><br>List of supported languages:</p><ul style="list-style: square;padding-left: 35px;max-height: 180px;overflow: auto;font-size: 1.2em;"><li>Afrikaans</li><li>Bahasa Indonesia</li><li>Bahasa Melayu</li><li>Català</li><li>Čeština</li><li>Deutsch</li><li>English (Australia)</li><li>English (Canada)</li><li>English (India)</li><li>English (New Zealand)</li><li>English (South Africa)</li><li>English (United Kingdom)</li><li>English (United States)</li><li>Español (Argentina)</li><li>Español (Bolivia)</li><li>Español (Chile)</li><li>Español (Colombia)</li><li>Español (Costa Rica)</li><li>Español (Ecuador)</li><li>Español (El Salvador)</li><li>Español (España)</li><li>Español (Estados Unidos)</li><li>Español (Guatemala)</li><li>Español (Honduras)</li><li>Español (México)</li><li>Español (Nicaragua)</li><li>Español (Panamá)</li><li>Español (Paraguay)</li><li>Español (Perú)</li><li>Español (Puerto Rico)</li><li>Español (República Dominicana)</li><li>Español (Uruguay)</li><li>Español (Venezuela)</li><li>Euskara</li><li>Français</li><li>Galego</li><li>Hrvatski</li><li>IsiZulu</li><li>Íslenska</li><li>Italiano (Italia)</li><li>Italiano (Svizzera)</li><li>Magyar</li><li>Nederlands</li><li>Norsk bokmål</li><li>Polski</li><li>Português (Brasil)</li><li>Português (Portugal)</li><li>Română</li><li>Slovenčina</li><li>Suomi</li><li>Svenska</li><li>Türkçe</li><li>български</li><li>Pусский</li><li>Српски</li><li>한국어</li><li>中文 (普通话 (中国大陆))</li><li>中文 (普通话 (香港))</li><li>中文 (中文 (台灣))</li><li>中文 (粵語 (香港))</li><li>日本語</li><li>Lingua latīna</li></ul>' };